/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ChinaFlag: typeof import('./utils/flagIcons').ChinaFlag
  const CustomFlag: typeof import('./utils/flagIcons').CustomFlag
  const EffectScope: typeof import('vue').EffectScope
  const FILE_CATEGORY_RULES: typeof import('./utils/index').FILE_CATEGORY_RULES
  const FormItem: typeof import('./composables/useForm').FormItem
  const FranceFlag: typeof import('./utils/flagIcons').FranceFlag
  const GermanyFlag: typeof import('./utils/flagIcons').GermanyFlag
  const JapanFlag: typeof import('./utils/flagIcons').JapanFlag
  const KoreaFlag: typeof import('./utils/flagIcons').KoreaFlag
  const RAGService: typeof import('./services/index').RAGService
  const RussiaFlag: typeof import('./utils/flagIcons').RussiaFlag
  const SpainFlag: typeof import('./utils/flagIcons').SpainFlag
  const UKFlag: typeof import('./utils/flagIcons').UKFlag
  const ZodSchemaToFormFields: typeof import('./utils/zod-to-form').ZodSchemaToFormFields
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const anyUrlToBlobUrl: typeof import('./utils/index').anyUrlToBlobUrl
  const arrayBufferToBlob: typeof import('./utils/index').arrayBufferToBlob
  const assetsHandler: typeof import('./utils/index').assetsHandler
  const base64ToText: typeof import('./utils/index').base64ToText
  const blobToDataURL: typeof import('./utils/index').blobToDataURL
  const chatService: typeof import('./services/index').chatService
  const cleanOptions: typeof import('./utils/index').cleanOptions
  const cloneDeep: typeof import('./utils/index').cloneDeep
  const computed: typeof import('vue').computed
  const copyFilesToUserData: typeof import('./utils/index').copyFilesToUserData
  const copyText: typeof import('./utils/index').copyText
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const dataURLToBlob: typeof import('./utils/index').dataURLToBlob
  const debounce: typeof import('./utils/index').debounce
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const execPromise: typeof import('./utils/index').execPromise
  const formatFileSize: typeof import('./utils/index').formatFileSize
  const formatTime: typeof import('./utils/time').formatTime
  const getActivePinia: typeof import('pinia').getActivePinia
  const getBuiltinTools: typeof import('./services/index').getBuiltinTools
  const getCategoryLabel: typeof import('./utils/index').getCategoryLabel
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getFileCategory: typeof import('./utils/index').getFileCategory
  const getFileIcon: typeof import('./utils/index').getFileIcon
  const getHost: typeof import('./utils/index').getHost
  const getLanguageFlag: typeof import('./utils/flagIcons').getLanguageFlag
  const getSplitTypeByMediaType: typeof import('./utils/index').getSplitTypeByMediaType
  const h: typeof import('vue').h
  const indexedDBStorage: typeof import('./utils/index').indexedDBStorage
  const inject: typeof import('vue').inject
  const isImageUrl: typeof import('./utils/index').isImageUrl
  const isMobile: typeof import('./composables/useDeviceType').isMobile
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isVideoUrl: typeof import('./utils/index').isVideoUrl
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapValues: typeof import('./utils/index').mapValues
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const messageApi: typeof import('./utils/messages').messageApi
  const nanoid: typeof import('./utils/nanoid').nanoid
  const nextTick: typeof import('vue').nextTick
  const notificationApi: typeof import('./utils/notifications').notificationApi
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onUseAIBefore: typeof import('./utils/onuseAIbefore').onUseAIBefore
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const retry: typeof import('./utils/index').retry
  const saveFilesToUserData: typeof import('./utils/index').saveFilesToUserData
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const speechService: typeof import('./services/speechService').speechService
  const splitByParagraph: typeof import('./utils/speech').splitByParagraph
  const splitBySentence: typeof import('./utils/speech').splitBySentence
  const splitTextForTTS: typeof import('./services/tts/index').splitTextForTTS
  const storeToRefs: typeof import('pinia').storeToRefs
  const stripAnsi: typeof import('./utils/index').stripAnsi
  const throttle: typeof import('./utils/index').throttle
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const ttsService: typeof import('./services/tts/index').ttsService
  const unref: typeof import('vue').unref
  const uploadDir: typeof import('./utils/index').uploadDir
  const useAgent: typeof import('./composables/useAgent').useAgent
  const useAgentStore: typeof import('./stores/agent').useAgentStore
  const useAppHeader: typeof import('./composables/useAppHeader').useAppHeader
  const useAttrs: typeof import('vue').useAttrs
  const useBackButton: typeof import('./composables/useBackButton').useBackButton
  const useChat: typeof import('./composables/useChat').useChat
  const useChatsStores: typeof import('./stores/chats').useChatsStores
  const useContextMenu: typeof import('./composables/useContextMenu').useContextMenu
  const useContinuousVoiceRecorder: typeof import('./composables/useContinuousVoiceRecorder').useContinuousVoiceRecorder
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDownload: typeof import('./composables/useDownload').useDownload
  const useForm: typeof import('./composables/useForm').useForm
  const useIcon: typeof import('./composables/useIcon').useIcon
  const useId: typeof import('vue').useId
  const useKnowledge: typeof import('./composables/useKnowledge').useKnowledge
  const useKnowledgeStore: typeof import('./stores/knowledge').useKnowledgeStore
  const useLink: typeof import('vue-router').useLink
  const useLocalStorage: typeof import('./composables/vueuse').useLocalStorage
  const useMobile: typeof import('./composables/useMobile').useMobile
  const useModal: typeof import('./composables/useModal').useModal
  const useModel: typeof import('vue').useModel
  const useNotes: typeof import('./composables/useNotes').useNotes
  const useNotesStore: typeof import('./stores/notes').useNotesStore
  const useNotificationStore: typeof import('./stores/notifications').useNotificationStore
  const usePlugin: typeof import('./composables/usePlugins').usePlugin
  const usePlugins: typeof import('./composables/usePlugins').usePlugins
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useScroll: typeof import('./composables/index').useScroll
  const useSettingsStore: typeof import('./stores/settings').useSettingsStore
  const useSlots: typeof import('vue').useSlots
  const useSpeechService: typeof import('./services/speechService').useSpeechService
  const useSpeechStore: typeof import('./stores/speech').useSpeechStore
  const useTTS: typeof import('./composables/useTTS').useTTS
  const useTable: typeof import('./composables/useTable').useTable
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTemporaryChat: typeof import('./composables/useTemporaryChat').useTemporaryChat
  const useTerminal: typeof import('./composables/useTerminal').useTerminal
  const useTitle: typeof import('./composables/useTitle').useTitle
  const useToolApproval: typeof import('./composables/useToolApproval').useToolApproval
  const useToolApprovalStore: typeof import('./stores/toolApproval').useToolApprovalStore
  const useTranslation: typeof import('./composables/useTranslation').useTranslation
  const useUpload: typeof import('./composables/useUpload').useUpload
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const zodSchemaToFormFields: typeof import('./utils/zod-to-form').zodSchemaToFormFields
  const zodSchemaToFormfields: typeof import('./utils/zod-to-form').zodSchemaToFormfields
  const zodSchemasToFormfields: typeof import('./utils/zod-to-form').zodSchemasToFormfields
  const zodToFormFields: typeof import('./composables/useForm').zodToFormFields
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { BackButtonOptions } from './composables/useBackButton'
  import('./composables/useBackButton')
  // @ts-ignore
  export type { MenuItem } from './composables/useContextMenu'
  import('./composables/useContextMenu')
  // @ts-ignore
  export type { DownloadProgress, UseDownloadOptions } from './composables/useDownload'
  import('./composables/useDownload')
  // @ts-ignore
  export type { TextField, BooleanField, SliderField, SelectField, TextareaField, ArrayField, ObjectField, CheckboxGroupField, ModelSelectorField, ColorField, PathSelectorField, UploadField, CustomField, GroupField, ArrayGroupField, FormField, FormConfig, FormActions } from './composables/useForm'
  import('./composables/useForm')
  // @ts-ignore
  export type { TableColumn, TableConfig, TableActions } from './composables/useTable'
  import('./composables/useTable')
  // @ts-ignore
  export type { TerminalTab } from './composables/useTerminal'
  import('./composables/useTerminal')
  // @ts-ignore
  export type { TranslationOptions } from './composables/useTranslation'
  import('./composables/useTranslation')
  // @ts-ignore
  export type { UploadFile, UseUploadOptions } from './composables/useUpload'
  import('./composables/useUpload')
  // @ts-ignore
  export type { FileCategory, FileItem } from './utils/index'
  import('./utils/index')
  // @ts-ignore
  export type { MessageType, MessageItem, CloseMessage, MessageHandler, MessageApi } from './utils/messages'
  import('./utils/messages')
  // @ts-ignore
  export type { NotificationItem, CloseNotification, NotificationHandler, NotificationApi } from './utils/notifications'
  import('./utils/notifications')
  // @ts-ignore
  export type { Note, NoteFolder } from './stores/notes'
  import('./stores/notes')
  // @ts-ignore
  export type { NotificationType, StatusItem } from './stores/notifications'
  import('./stores/notifications')
  // @ts-ignore
  export type { AudioChunk } from './stores/speech'
  import('./stores/speech')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly ChinaFlag: UnwrapRef<typeof import('./utils/flagIcons')['ChinaFlag']>
    readonly CustomFlag: UnwrapRef<typeof import('./utils/flagIcons')['CustomFlag']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly FILE_CATEGORY_RULES: UnwrapRef<typeof import('./utils/index')['FILE_CATEGORY_RULES']>
    readonly FormItem: UnwrapRef<typeof import('./composables/useForm')['FormItem']>
    readonly FranceFlag: UnwrapRef<typeof import('./utils/flagIcons')['FranceFlag']>
    readonly GermanyFlag: UnwrapRef<typeof import('./utils/flagIcons')['GermanyFlag']>
    readonly JapanFlag: UnwrapRef<typeof import('./utils/flagIcons')['JapanFlag']>
    readonly KoreaFlag: UnwrapRef<typeof import('./utils/flagIcons')['KoreaFlag']>
    readonly RAGService: UnwrapRef<typeof import('./services/index')['RAGService']>
    readonly RussiaFlag: UnwrapRef<typeof import('./utils/flagIcons')['RussiaFlag']>
    readonly SpainFlag: UnwrapRef<typeof import('./utils/flagIcons')['SpainFlag']>
    readonly UKFlag: UnwrapRef<typeof import('./utils/flagIcons')['UKFlag']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly anyUrlToBlobUrl: UnwrapRef<typeof import('./utils/index')['anyUrlToBlobUrl']>
    readonly arrayBufferToBlob: UnwrapRef<typeof import('./utils/index')['arrayBufferToBlob']>
    readonly assetsHandler: UnwrapRef<typeof import('./utils/index')['assetsHandler']>
    readonly base64ToText: UnwrapRef<typeof import('./utils/index')['base64ToText']>
    readonly blobToDataURL: UnwrapRef<typeof import('./utils/index')['blobToDataURL']>
    readonly chatService: UnwrapRef<typeof import('./services/index')['chatService']>
    readonly cloneDeep: UnwrapRef<typeof import('./utils/index')['cloneDeep']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly copyFilesToUserData: UnwrapRef<typeof import('./utils/index')['copyFilesToUserData']>
    readonly copyText: UnwrapRef<typeof import('./utils/index')['copyText']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly dataURLToBlob: UnwrapRef<typeof import('./utils/index')['dataURLToBlob']>
    readonly debounce: UnwrapRef<typeof import('./utils/index')['debounce']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly execPromise: UnwrapRef<typeof import('./utils/index')['execPromise']>
    readonly formatFileSize: UnwrapRef<typeof import('./utils/index')['formatFileSize']>
    readonly formatTime: UnwrapRef<typeof import('./utils/time')['formatTime']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getBuiltinTools: UnwrapRef<typeof import('./services/index')['getBuiltinTools']>
    readonly getCategoryLabel: UnwrapRef<typeof import('./utils/index')['getCategoryLabel']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getFileCategory: UnwrapRef<typeof import('./utils/index')['getFileCategory']>
    readonly getFileIcon: UnwrapRef<typeof import('./utils/index')['getFileIcon']>
    readonly getHost: UnwrapRef<typeof import('./utils/index')['getHost']>
    readonly getLanguageFlag: UnwrapRef<typeof import('./utils/flagIcons')['getLanguageFlag']>
    readonly getSplitTypeByMediaType: UnwrapRef<typeof import('./utils/index')['getSplitTypeByMediaType']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly indexedDBStorage: UnwrapRef<typeof import('./utils/index')['indexedDBStorage']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isImageUrl: UnwrapRef<typeof import('./utils/index')['isImageUrl']>
    readonly isMobile: UnwrapRef<typeof import('./composables/useDeviceType')['isMobile']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isVideoUrl: UnwrapRef<typeof import('./utils/index')['isVideoUrl']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapValues: UnwrapRef<typeof import('./utils/index')['mapValues']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly messageApi: UnwrapRef<typeof import('./utils/messages')['messageApi']>
    readonly nanoid: UnwrapRef<typeof import('./utils/nanoid')['nanoid']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly notificationApi: UnwrapRef<typeof import('./utils/notifications')['notificationApi']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onUseAIBefore: UnwrapRef<typeof import('./utils/onuseAIbefore')['onUseAIBefore']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly retry: UnwrapRef<typeof import('./utils/index')['retry']>
    readonly saveFilesToUserData: UnwrapRef<typeof import('./utils/index')['saveFilesToUserData']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly speechService: UnwrapRef<typeof import('./services/speechService')['speechService']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly stripAnsi: UnwrapRef<typeof import('./utils/index')['stripAnsi']>
    readonly throttle: UnwrapRef<typeof import('./utils/index')['throttle']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly uploadDir: UnwrapRef<typeof import('./utils/index')['uploadDir']>
    readonly useAgent: UnwrapRef<typeof import('./composables/useAgent')['useAgent']>
    readonly useAgentStore: UnwrapRef<typeof import('./stores/agent')['useAgentStore']>
    readonly useAppHeader: UnwrapRef<typeof import('./composables/useAppHeader')['useAppHeader']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useBackButton: UnwrapRef<typeof import('./composables/useBackButton')['useBackButton']>
    readonly useChat: UnwrapRef<typeof import('./composables/useChat')['useChat']>
    readonly useChatsStores: UnwrapRef<typeof import('./stores/chats')['useChatsStores']>
    readonly useContextMenu: UnwrapRef<typeof import('./composables/useContextMenu')['useContextMenu']>
    readonly useContinuousVoiceRecorder: UnwrapRef<typeof import('./composables/useContinuousVoiceRecorder')['useContinuousVoiceRecorder']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDownload: UnwrapRef<typeof import('./composables/useDownload')['useDownload']>
    readonly useForm: UnwrapRef<typeof import('./composables/useForm')['useForm']>
    readonly useIcon: UnwrapRef<typeof import('./composables/useIcon')['useIcon']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useKnowledge: UnwrapRef<typeof import('./composables/useKnowledge')['useKnowledge']>
    readonly useKnowledgeStore: UnwrapRef<typeof import('./stores/knowledge')['useKnowledgeStore']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useLocalStorage: UnwrapRef<typeof import('./composables/vueuse')['useLocalStorage']>
    readonly useMobile: UnwrapRef<typeof import('./composables/useMobile')['useMobile']>
    readonly useModal: UnwrapRef<typeof import('./composables/useModal')['useModal']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNotesStore: UnwrapRef<typeof import('./stores/notes')['useNotesStore']>
    readonly useNotificationStore: UnwrapRef<typeof import('./stores/notifications')['useNotificationStore']>
    readonly usePlugins: UnwrapRef<typeof import('./composables/usePlugins')['usePlugins']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useScroll: UnwrapRef<typeof import('./composables/index')['useScroll']>
    readonly useSettingsStore: UnwrapRef<typeof import('./stores/settings')['useSettingsStore']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSpeechStore: UnwrapRef<typeof import('./stores/speech')['useSpeechStore']>
    readonly useTable: UnwrapRef<typeof import('./composables/useTable')['useTable']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTemporaryChat: UnwrapRef<typeof import('./composables/useTemporaryChat')['useTemporaryChat']>
    readonly useTerminal: UnwrapRef<typeof import('./composables/useTerminal')['useTerminal']>
    readonly useTitle: UnwrapRef<typeof import('./composables/useTitle')['useTitle']>
    readonly useTranslation: UnwrapRef<typeof import('./composables/useTranslation')['useTranslation']>
    readonly useUpload: UnwrapRef<typeof import('./composables/useUpload')['useUpload']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly zodSchemasToFormfields: UnwrapRef<typeof import('./utils/zod-to-form')['zodSchemasToFormfields']>
  }
}