packages:
  - apps/*
  - packages/*
  - packages/qi-cli/example/*

catalog:
  '@ai-sdk/anthropic': 3.0.36
  '@ai-sdk/deepseek': 2.0.17
  '@ai-sdk/elevenlabs': ^2.0.17
  '@ai-sdk/google': 3.0.20
  '@ai-sdk/hume': 2.0.17
  '@ai-sdk/mcp': 1.0.18
  '@ai-sdk/openai': 3.0.25
  '@ai-sdk/openai-compatible': 2.0.26
  '@ai-sdk/vue': 3.0.69
  '@ai-sdk/xai': 3.0.46
  '@capacitor/android': ^8.0.2
  '@capacitor/app': ^8.0.0
  '@capacitor/cli': ^8.0.2
  '@capacitor/core': ^8.0.2
  '@capacitor/ios': ^8.0.2
  '@electron-toolkit/eslint-config-prettier': 3.0.0
  '@electron-toolkit/eslint-config-ts': ^3.1.0
  '@electron-toolkit/preload': ^3.0.2
  '@electron-toolkit/tsconfig': ^2.0.0
  '@electron-toolkit/utils': ^4.0.0
  '@electron/rebuild': ^4.0.3
  '@electron/remote': ^2.1.3
  '@incremark/core': ^0.3.10
  '@incremark/theme': ^0.3.10
  '@incremark/vue': ^0.3.10
  '@langchain/core': ^1.1.19
  '@langchain/textsplitters': ^1.0.1
  '@modelcontextprotocol/sdk': ^1.25.3
  '@prettier/plugin-oxc': ^0.1.3
  '@tiptap/extension-code-block': ^3.19.0
  '@tiptap/extension-code-block-lowlight': ^3.19.0
  '@tiptap/extension-color': ^3.19.0
  '@tiptap/extension-horizontal-rule': ^3.19.0
  '@tiptap/extension-image': ^3.19.0
  '@tiptap/extension-placeholder': ^3.19.0
  '@tiptap/extension-table': ^3.19.0
  '@tiptap/extension-table-cell': ^3.19.0
  '@tiptap/extension-table-header': ^3.19.0
  '@tiptap/extension-table-row': ^3.19.0
  '@tiptap/extension-task-item': ^3.19.0
  '@tiptap/extension-task-list': ^3.19.0
  '@tiptap/extension-text-align': ^3.19.0
  '@tiptap/extension-text-style': ^3.19.0
  '@tiptap/starter-kit': ^3.19.0
  '@tiptap/vue-3': ^3.19.0
  '@tsconfig/node22': ^22.0.5
  '@types/inquirer': ^9.0.9
  '@types/jszip': ^3.4.1
  '@types/mime-types': ^3.0.1
  '@types/node': ^25.2.0
  '@vicons/carbon': ^0.13.0
  '@vicons/fluent': ^0.13.0
  '@vicons/ionicons5': ^0.13.0
  '@vicons/material': ^0.13.0
  '@vicons/tabler': ^0.13.0
  '@vicons/utils': ^0.1.4
  '@vitejs/plugin-vue': ^6.0.4
  '@vitejs/plugin-vue-jsx': ^5.1.4
  '@vue/eslint-config-prettier': ^10.2.0
  '@vue/eslint-config-typescript': ^14.6.0
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^14.2.0
  ai: 6.0.69
  ai-sdk-ollama: ^3.3.0
  better-sqlite3: ^12.6.2
  blob-util: ^2.0.2
  chalk: ^5.6.2
  commander: ^14.0.3
  dayjs: ^1.11.19
  electron: ^40.1.0
  electron-builder: ^26.7.0
  electron-updater: ^6.7.3
  electron-vite: ^5.0.0
  es-toolkit: ^1.44.0
  eslint: ^9.39.2
  eslint-plugin-oxlint: ~1.43.0
  eslint-plugin-vue: ^10.7.0
  hast-util-to-html: ^9.0.5
  highlight.js: ^11.11.1
  inquirer: ^13.2.2
  jszip: ^3.10.1
  localforage: ^1.10.0
  lowlight: ^3.3.0
  mime-types: ^3.0.2
  nanoid: ^5.1.6
  node-pty: ^1.1.0
  npm-run-all2: ^8.0.4
  openai: ^6.17.0
  ora: ^9.1.0
  oxlint: ~1.43.0
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  pinia-plugin-persistedstate-async: ^1.6.3
  prettier: ^3.8.1
  sqlite-vec: ^0.1.7-alpha.2
  strip-ansi: ^7.1.2
  turbo: ^2.8.3
  typescript: ^5.9.3
  unplugin-auto-import: ^21.0.0
  unplugin-vue-components: ^31.0.0
  vite: ^7.3.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-vue-devtools: ^8.0.5
  vue: ^3.5.27
  vue-eslint-parser: ^10.2.0
  vue-router: ^5.0.2
  vue-tsc: ^3.2.4
  xterm: ^5.3.0
  xterm-addon-fit: ^0.8.0
  zhipu-ai-provider: 0.2.2
  zod: ^4.3.6
